# -*- coding: utf-8 -*-
"""Lec_1.1_WS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uoyo1YatwcgCOL2dIlA5qLRXtz7H-6lq

**1. Print Function**

-- printting strings use " " , quotes
"""

print("Hello World!")

"""-- Print your name."""

print(22) #print a number like your age no need to use quotes

"""**2. Data Types**

fucntion type()
"""

x=10
type(10)

"""Integer is number without deciaml point."""

y=4.5
type(y)

"""Float is number with decimal point."""

y="Tanya"
type(y)

"""str means string that is text data type."""

y = False
type(y)

"""bool means boolean;  a form of data with only two possible values (usually "true" and "false")"""

#Data types that will be useful for us most of the time in Data Science
int
float
string
bool  True , False